HamaHama-Dev/pupmory

backend/build.gradle, backend/src/main/java/com/hamahama/pupmory/domain/user/ServiceUser.java, backend/src/main/java/com/hamahama/pupmory/domain/user/ServiceUserRepository.java, backend/src/main/resources/application.yml
=> [~6/13] DB 연결 및 테스트 테이블 생성

backend/src/main/java/com/hamahama/pupmory/controller/ConversationController.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/MetaData.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/MetaDataId.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/MetaDataRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/result/SetResultId.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/result/UserSetResult.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/result/UserSetResultRepository.java, backend/src/main/java/com/hamahama/pupmory/dto/SetRequestDto.java, backend/src/main/java/com/hamahama/pupmory/dto/SetResponseDto.java, backend/src/main/java/com/hamahama/pupmory/service/ConversationService.java
=> [~6/13] 대화 세트 목록 가져오기 API

backend/build.gradle, backend/src/main/java/com/hamahama/pupmory/controller/ConversationController.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/MetaData.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/MetaDataId.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/MetaDataRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/result/SetResultId.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/result/UserSetResult.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/result/UserSetResultRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/user/ServiceUser.java, backend/src/main/java/com/hamahama/pupmory/domain/user/ServiceUserRepository.java, backend/src/main/java/com/hamahama/pupmory/dto/SetRequestDto.java, backend/src/main/java/com/hamahama/pupmory/dto/SetResponseDto.java, backend/src/main/java/com/hamahama/pupmory/service/ConversationService.java, backend/src/main/resources/application.yml
feat: Add Prototype main home (#7)
=> feat: Add Prototype main home

backend/build.gradle, backend/src/main/java/com/hamahama/pupmory/controller/ConversationController.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/data/AnswerData.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/data/AnswerDataId.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/data/AnswerDataRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/data/GptAnswerData.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/data/GptAnswerDataRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/result/AnswerResultId.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/result/UserAnswerResult.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/result/UserAnswerResultRepository.java, backend/src/main/java/com/hamahama/pupmory/dto/AnswerRequestDto.java, backend/src/main/java/com/hamahama/pupmory/dto/AnswerResponseDto.java, backend/src/main/java/com/hamahama/pupmory/dto/ChatRequest.java, backend/src/main/java/com/hamahama/pupmory/dto/ChatResponse.java, backend/src/main/java/com/hamahama/pupmory/dto/Choice.java, backend/src/main/java/com/hamahama/pupmory/dto/Message.java, backend/src/main/java/com/hamahama/pupmory/service/ChatgptService.java, backend/src/main/java/com/hamahama/pupmory/service/ConversationService.java, backend/src/main/java/com/hamahama/pupmory/service/GptService.java, backend/src/main/java/com/hamahama/pupmory/service/impl/DefaultChatgptService.java, backend/src/main/resources/application.yml
=> [~6/13] 특정 대화 세트의 질문에 대한 캐릭터 답변 가져오기 API

backend/src/main/java/com/hamahama/pupmory/controller/ConversationController.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/data/AnswerDataRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/data/GptAnswerData.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/data/GptAnswerDataRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/result/AnswerResultId.java, backend/src/main/java/com/hamahama/pupmory/dto/AnswerRequestDto.java, backend/src/main/java/com/hamahama/pupmory/dto/AnswerResponseDto.java, backend/src/main/java/com/hamahama/pupmory/service/ConversationService.java, backend/src/main/java/com/hamahama/pupmory/service/GptService.java
=> [~6/17] 프로토타입 변경사항으로 인한 GPT API 패치

backend/src/main/java/com/hamahama/pupmory/controller/ConversationController.java
=> [~6/18] 대화 API method 변경

backend/src/main/java/com/hamahama/pupmory/controller/CommunityController.java, backend/src/main/java/com/hamahama/pupmory/domain/community/Help.java, backend/src/main/java/com/hamahama/pupmory/domain/community/HelpRepository.java, backend/src/main/java/com/hamahama/pupmory/dto/community/HelpAnswerSaveRequestDto.java, backend/src/main/java/com/hamahama/pupmory/dto/community/HelpSaveRequestDto.java, backend/src/main/java/com/hamahama/pupmory/service/CommunityService.java
=> [~10/12] 도와줄개 API 구현

backend/build.gradle, backend/src/main/java/com/hamahama/pupmory/conf/S3Configuration.java, backend/src/main/java/com/hamahama/pupmory/controller/CommunityController.java, backend/src/main/java/com/hamahama/pupmory/controller/MemorialController.java, backend/src/main/java/com/hamahama/pupmory/controller/SearchController.java, backend/src/main/java/com/hamahama/pupmory/domain/community/Help.java, backend/src/main/java/com/hamahama/pupmory/domain/community/HelpRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/memorial/Post.java, backend/src/main/java/com/hamahama/pupmory/domain/memorial/PostRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/memorial/UserLikeRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/search/KeywordRank.java, backend/src/main/java/com/hamahama/pupmory/domain/search/KeywordRankRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/search/SearchHistory.java, backend/src/main/java/com/hamahama/pupmory/domain/search/SearchHistoryRepository.java, backend/src/main/java/com/hamahama/pupmory/dto/community/HelpAnswerSaveRequestDto.java, backend/src/main/java/com/hamahama/pupmory/dto/community/HelpSaveRequestDto.java, backend/src/main/java/com/hamahama/pupmory/dto/memorial/PostRequestDto.java, backend/src/main/java/com/hamahama/pupmory/dto/search/SearchHistoryResponseDto.java, backend/src/main/java/com/hamahama/pupmory/service/CommunityService.java, backend/src/main/java/com/hamahama/pupmory/service/MemorialService.java, backend/src/main/java/com/hamahama/pupmory/service/SearchService.java, backend/src/main/java/com/hamahama/pupmory/util/S3Uploader.java, backend/src/main/resources/application.yml
- #34
- #35 merge 이후 develop에서 유실된 커밋 복구
실수를 기록하기 위해서임.
=> Fix for PR#35 merge rollback issue

client/lib/memorial/memorial_detail.dart, client/lib/memorial/memorial_main.dart
=> [~10/03] 메모리얼 본인 페이지 구현

client/lib/help/answer_help_request.dart, client/lib/help/help_main.dart, client/lib/help/received_help.dart, client/lib/help/write_help_request.dart
=> [~10/19] 도움 내역 구현

client/lib/sign/google_log_in.dart, client/lib/sign/sign_in.dart, client/lib/sign/sign_up2.dart
=> [~10/19] 로그인 페이지 구현

backend/build.gradle, backend/src/main/java/com/hamahama/pupmory/controller/AuthController.java, backend/src/main/java/com/hamahama/pupmory/controller/CommunityController.java, backend/src/main/java/com/hamahama/pupmory/controller/MemorialController.java, backend/src/main/java/com/hamahama/pupmory/domain/auth/ValidationCode.java, backend/src/main/java/com/hamahama/pupmory/domain/auth/ValidationCodeRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/community/HelpRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/memorial/PostRepository.java, backend/src/main/java/com/hamahama/pupmory/dto/memorial/CommentResponseDto.java, backend/src/main/java/com/hamahama/pupmory/pojo/HelpLog.java, backend/src/main/java/com/hamahama/pupmory/service/AuthService.java, backend/src/main/java/com/hamahama/pupmory/service/CommunityService.java, backend/src/main/java/com/hamahama/pupmory/service/MemorialService.java, backend/src/main/java/com/hamahama/pupmory/util/auth/MailKit.java, backend/src/main/resources/application.yml, backend/src/main/resources/templates/auth-mail.html
=> [~10/29] 메일인증 시스템 & 댓글 작성자 정보 추가

backend/src/main/java/com/hamahama/pupmory/dto/memorial/FeedPostResponseDto.java, backend/src/main/java/com/hamahama/pupmory/dto/memorial/PostRequestDto.java, backend/src/main/java/com/hamahama/pupmory/service/MemorialService.java, backend/src/main/java/com/hamahama/pupmory/service/SearchService.java
=> [~10/29] 피드 uid 추가 & 메모리얼 저장 시 date 필드 추가

backend/src/main/java/com/hamahama/pupmory/controller/CommunityController.java, backend/src/main/java/com/hamahama/pupmory/controller/ConversationController.java, backend/src/main/java/com/hamahama/pupmory/controller/UserController.java, backend/src/main/java/com/hamahama/pupmory/dto/community/HelpResponseDto.java, backend/src/main/java/com/hamahama/pupmory/dto/user/UserInfoUpdateDto.java, backend/src/main/java/com/hamahama/pupmory/service/CommunityService.java, backend/src/main/java/com/hamahama/pupmory/service/ConversationService.java, backend/src/main/java/com/hamahama/pupmory/service/UserService.java
=> [~10/29] 사용자 추가 정보 저장 & 도움내역 필드 추가

backend/src/main/java/com/hamahama/pupmory/controller/CommunityController.java, backend/src/main/java/com/hamahama/pupmory/service/CommunityService.java
=> [~11/3] 워드클라우드 커맨드 수정 및 API 스펙 변경

client/lib/sign/sign_in.dart, client/lib/sign/sign_up2.dart
=> [~10/19] 메일 인증 추가 & 인트로 연결

backend/src/main/java/com/hamahama/pupmory/controller/UserController.java, backend/src/main/java/com/hamahama/pupmory/domain/community/HelpRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/user/ServiceUser.java, backend/src/main/java/com/hamahama/pupmory/dto/memorial/FeedPostResponseDto.java, backend/src/main/java/com/hamahama/pupmory/dto/user/ConversationStatusUpdateDto.java, backend/src/main/java/com/hamahama/pupmory/dto/user/UserInfoResponseDto.java, backend/src/main/java/com/hamahama/pupmory/service/CommunityService.java, backend/src/main/java/com/hamahama/pupmory/service/MemorialService.java, backend/src/main/java/com/hamahama/pupmory/service/UserService.java, backend/src/main/java/com/hamahama/pupmory/util/auth/MailKit.java
=> [~11/14] 사용자 정보 조회 API 패치 & 대화 상태 업데이트 API 추가 외

backend/src/main/java/com/hamahama/pupmory/controller/ConversationController.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/data/GptEmotionData.java, backend/src/main/java/com/hamahama/pupmory/domain/conversation/data/GptEmotionDataRepository.java, backend/src/main/java/com/hamahama/pupmory/dto/conversation/EmotionRequestDto.java, backend/src/main/java/com/hamahama/pupmory/dto/conversation/EmotionResponseDto.java, backend/src/main/java/com/hamahama/pupmory/service/GptService.java
=> [~11/14] 초기 GPT API 구현

backend/src/main/java/com/hamahama/pupmory/controller/MyPageController.java, backend/src/main/java/com/hamahama/pupmory/controller/UserController.java, backend/src/main/java/com/hamahama/pupmory/domain/community/HelpRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/community/WordCloudRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/memorial/CommentRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/memorial/PostRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/memorial/UserLikeRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/mypage/Announcement.java, backend/src/main/java/com/hamahama/pupmory/domain/mypage/AnnouncementRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/search/SearchHistoryRepository.java, backend/src/main/java/com/hamahama/pupmory/dto/mypage/AnnouncementDetailDto.java, backend/src/main/java/com/hamahama/pupmory/dto/mypage/AnnouncementMetaDto.java, backend/src/main/java/com/hamahama/pupmory/service/MyPageService.java, backend/src/main/java/com/hamahama/pupmory/service/UserService.java
=> [~11/19] 마이페이지 API 구현

backend/src/main/java/com/hamahama/pupmory/service/UserService.java
=> [~11/19] 사용자 대화 정보 저장 API 패치

backend/src/main/java/com/hamahama/pupmory/controller/MemorialController.java, backend/src/main/java/com/hamahama/pupmory/domain/memorial/CommentRepository.java, backend/src/main/java/com/hamahama/pupmory/domain/memorial/UserLikeRepository.java, backend/src/main/java/com/hamahama/pupmory/dto/memorial/PostDetailResponseDto.java, backend/src/main/java/com/hamahama/pupmory/service/MemorialService.java
=> [~11/19] 메모리얼 삭제 API 구현 및 좋아요 수 누락 패치

backend/src/main/java/com/hamahama/pupmory/controller/MyPageController.java, backend/src/main/java/com/hamahama/pupmory/controller/SearchController.java, backend/src/main/java/com/hamahama/pupmory/domain/memorial/CommentRepository.java, backend/src/main/java/com/hamahama/pupmory/dto/mypage/CommentMetaDto.java, backend/src/main/java/com/hamahama/pupmory/service/MyPageService.java, backend/src/main/java/com/hamahama/pupmory/service/SearchService.java
=> [~11/20] 사용자 검색기록 전체 삭제 및 댓글 이력 조회 API 구현

backend/src/main/java/com/hamahama/pupmory/service/CommunityService.java, backend/src/main/python/wcloud.py
=> [~11/20] 워드클라우드 합산 기능 추가 및 인코딩 패치

backend/src/main/java/com/hamahama/pupmory/service/CommunityService.java, backend/src/main/python/wcloud.py
=> [~11/20] 빌드 환경 변경에 따른 워드클라우드 패치

.github/workflows/build-n-publish.yml, Dockerfile, deploy.sh
=> [~11/20] 빌드 및 배포 파일 작성
